# Generated by Django 4.2.5 on 2023-09-30 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progressreport',
            unique_together={('user', 'report_date')},
        ),
    ]
