# Generated by Django 4.2.5 on 2023-10-06 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lab_name",
                    models.CharField(
                        choices=[
                            ("Report 1", "Report 1"),
                            ("Report 2", "Report 2"),
                            ("Report 3", "Report 3"),
                        ],
                        max_length=100,
                    ),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("lab_email", models.EmailField(max_length=255, unique=True)),
                ("lab_password", models.CharField(max_length=128)),
                ("details", models.TextField(blank=True, null=True)),
                (
                    "lab_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Report 1", "Report 1"),
                            ("Report 2", "Report 2"),
                            ("Report 3", "Report 3"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("results", models.TextField()),
                ("lab_report", models.FileField(upload_to="lab_reports/")),
                ("lab_technician", models.CharField(max_length=100, null=True)),
                ("lab_location", models.CharField(max_length=100, null=True)),
                ("lab_test_type", models.CharField(max_length=100, null=True)),
                ("lab_reference_range", models.CharField(max_length=100, null=True)),
                ("is_urgent", models.BooleanField(default=False)),
                ("is_confidential", models.BooleanField(default=False)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lab.labregistration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
