# Generated by Django 4.2.5 on 2023-09-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthprofile",
            name="calories",
            field=models.PositiveIntegerField(
                blank=True, help_text="Daily calorie requirements", null=True
            ),
        ),
    ]
