# Generated by Django 4.2.5 on 2023-09-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_healthprofile_calories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthprofile",
            name="calories",
            field=models.FloatField(
                blank=True, help_text="Daily calorie requirements", null=True
            ),
        ),
    ]
