# Generated by Django 4.2.5 on 2023-09-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_healthprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthprofile",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
