# Generated by Django 4.2.5 on 2023-09-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_healthprofile_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Body Mass Index', max_digits=5, null=True),
        ),
    ]
