# Generated by Django 4.2.5 on 2023-09-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_healthprofile_bmi_healthprofile_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='blood_glucose',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Blood Glucose Level', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='Blood Pressure', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='cholesterol',
            field=models.JSONField(blank=True, help_text='Cholesterol Levels (JSON)', null=True),
        ),
    ]
