# Generated by Django 3.2.21 on 2023-10-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_healthprofile_blood_glucose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='cholesterol',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cholesterol Levels (JSON)', max_digits=5, null=True),
        ),
    ]
