# Generated by Django 3.2.21 on 2023-10-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_healthprofile_cholesterol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthprofile',
            name='cholesterol',
        ),
    ]
