# Generated by Django 3.2.22 on 2023-10-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_healthprofile_cholesterol'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='cholesterol',
            field=models.JSONField(blank=True, help_text='Cholesterol Levels (JSON)', null=True),
        ),
    ]
