# Generated by Django 3.2.22 on 2023-10-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_healthprofile_cholesterol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='cholesterol',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cholesterol Levels (JSON)', max_digits=5, null=True),
        ),
    ]
